package com.github.orions29.ekspedisi.views;

import com.github.orions29.ekspedisi.model.entity.User;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import javax.swing.*;

import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;

/**
 * Project: EkspedisiMasRoi
 * Package: com.github.orions29.ekspedisi.views
 * <p>
 * Antarmuka untuk Staf Gudang dengan injeksi DNA User absolut.
 * Dioptimalkan untuk integrasi Barcode Scanner (Input + Auto-Enter).
 * </p>
 *
 * <hr>
 * <table border="0">
 * <tr><td><b>Author</b></td><td>: Orions29</td></tr>
 * <tr><td><b>Date</b></td><td>: 30 May 2026</td></tr>
 * </table>
 * <hr>
 *
 * @author Orions29
 * @since 1.2
 */
public class GudangViews extends javax.swing.JFrame {

    private Logger logger = LoggerFactory.getLogger(GudangViews.class);

    private User loggedInUser;

    /**
     * Constructor yang memaksa injeksi data User.
     *
     * @param user Kapsul data User dari hasil DAO authenticate()
     */
    public GudangViews(User user) {
        // Keamanan Lapis 2: Bunuh jendela ini kalau ada yang iseng manggil tanpa login!
        if (user == null) {
            throw new IllegalArgumentException("Fatal: Akses ilegal! Jendela gudang wajib menerima data User yang valid.");
        }
        this.loggedInUser = user;

        initComponents();
        keyboardScanner();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    @SuppressWarnings("unchecked")
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        labelUsername = new javax.swing.JLabel();
        labelLokasi = new javax.swing.JLabel();
        btnLogout = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();

        panelOperasi = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        txtResi = new javax.swing.JTextField();
        btnCamera = new javax.swing.JButton();

        jLabel5 = new javax.swing.JLabel();
        comboStatus = new javax.swing.JComboBox<>();
        btnUpdate = new javax.swing.JButton();

        jScrollPane1 = new javax.swing.JScrollPane();
        txtConsole = new javax.swing.JTextArea();
        jLabel6 = new javax.swing.JLabel();

        btnCekPaketDiGudang = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("EMR Tracking System - Fasilitas Gudang");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18));
        jLabel1.setText("Panel Gudang Ekspedisi");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12));
        jLabel2.setText("Petugas :");

        labelUsername.setText(loggedInUser.getUsername() + " (" + loggedInUser.getId() + ")");

        labelLokasi.setFont(new java.awt.Font("Segoe UI", 2, 12));

        labelLokasi.setText("Bertugas di: " + (loggedInUser.getLocation() != null ? loggedInUser.getLocation() : "Lokasi Tidak Diketahui"));

        btnLogout.setText("Logout");

        panelOperasi.setBorder(javax.swing.BorderFactory.createTitledBorder("Operasi Scan Paket"));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14));
        jLabel4.setText("Nomor Resi / Barcode:");

        txtResi.setFont(new java.awt.Font("Consolas", 1, 16));

        btnCamera.setFont(new java.awt.Font("Segoe UI", 1, 12));
        btnCamera.setText("SCAN");
        btnCamera.setToolTipText("Scan Barcode via Kamera");
        btnCamera.setMargin(new java.awt.Insets(2, 2, 2, 2));

        jLabel5.setText("Set Status Berikutnya:");

        comboStatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[]{
                "Diterima Gudang",
                "Sedang Disortir",
                "Transit Gudang"
        }));


        btnUpdate.setFont(new java.awt.Font("Segoe UI", 1, 12));
        btnUpdate.setText("Update Status Logistik [ENTER]");

        btnCekPaketDiGudang.setFont(new java.awt.Font("Segoe UI", 1, 12));
        btnCekPaketDiGudang.setText("Cek Paket Di Gudang");

        javax.swing.GroupLayout panelOperasiLayout = new javax.swing.GroupLayout(panelOperasi);
        panelOperasi.setLayout(panelOperasiLayout);
        panelOperasiLayout.setHorizontalGroup(
                panelOperasiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(panelOperasiLayout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(panelOperasiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(btnUpdate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(btnCekPaketDiGudang, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(panelOperasiLayout.createSequentialGroup()
                                                .addGroup(panelOperasiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(jLabel4)
                                                        .addGroup(panelOperasiLayout.createSequentialGroup()
                                                                .addComponent(txtResi, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(btnCamera, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        )
                                                )
                                                .addGap(18, 18, 18)
                                                .addGroup(panelOperasiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(panelOperasiLayout.createSequentialGroup()
                                                                .addComponent(jLabel5)
                                                                .addGap(0, 77, Short.MAX_VALUE))
                                                        .addComponent(comboStatus, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                                .addContainerGap())
        );
        panelOperasiLayout.setVerticalGroup(
                panelOperasiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(panelOperasiLayout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(panelOperasiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel4)
                                        .addComponent(jLabel5))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(panelOperasiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(txtResi, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
                                        .addComponent(btnCamera, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
                                        .addComponent(comboStatus))
                                .addGap(18, 18, 18)
                                .addComponent(btnUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnCekPaketDiGudang, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        )
        );

        txtConsole.setEditable(false);
        txtConsole.setBackground(new java.awt.Color(0, 0, 0));
        txtConsole.setColumns(20);
        txtConsole.setFont(new java.awt.Font("Consolas", 0, 12));
        txtConsole.setForeground(new java.awt.Color(0, 255, 0));
        txtConsole.setRows(5);
        jScrollPane1.setViewportView(txtConsole);

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 12));
        jLabel6.setText("Console Log Scan (Real-time):");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jSeparator1)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(panelOperasi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jScrollPane1)
                                        .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(jLabel1)
                                                        .addComponent(jLabel6)
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                        .addGroup(layout.createSequentialGroup()
                                                                                .addComponent(jLabel2)
                                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                                .addComponent(labelUsername))
                                                                        .addComponent(labelLokasi))
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                                .addComponent(btnLogout)))
                                                .addGap(0, 0, Short.MAX_VALUE)))
                                .addContainerGap())
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(jLabel2)
                                                        .addComponent(labelUsername))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(labelLokasi))
                                        .addComponent(btnLogout))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(panelOperasi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 126, Short.MAX_VALUE)
                                .addContainerGap())
        );
        pack();
    }

    /**
     *
     * <h3>Scanner Untuk Pencet Enter</h3>
     * <p> ENter key untuk cek resi</p>
     *
     * @author Orions29
     * @since 2 Jun 2026
     *
     */
    private void keyboardScanner() {
        txtResi.addKeyListener(new KeyAdapter() {
            @Override
            public void keyPressed(KeyEvent e) {
                if (e.getKeyCode() == KeyEvent.VK_ENTER) {
                    btnUpdate.doClick();
                }
            }
        });
    }

    // Sebenarnya Buat Ngetest Doang Tp entah jangan ubah ubah bestie.
    public static void main(String[] args) {
        try {
            UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
        } catch (Exception ex) {
        }

        SwingUtilities.invokeLater(() -> {

            // Simulasi Dummy User agar form tetap bisa dites lewat psvm main
            User dummyUser = new User("G-2001", "gudang_budi", "hash", "gudang", "Fasilitas Sortir Godean");
            GudangViews frame = new GudangViews(dummyUser);
            frame.setLocationRelativeTo(null);
            frame.setVisible(true);
        });
    }

    public JButton getBtnCekPaketDiGudang() {
        return btnCekPaketDiGudang;
    }

    public JButton getBtnCamera() {
        return btnCamera;
    }

    public JButton getBtnLogout() {
        return btnLogout;
    }

    public javax.swing.JButton getBtnUpdate() {
        return btnUpdate;
    }

    public javax.swing.JTextField getTxtResi() {
        return txtResi;
    }

    public javax.swing.JComboBox<String> getComboStatus() {
        return comboStatus;
    }

    public javax.swing.JTextArea getTxtConsole() {
        return txtConsole;
    }

    // Variables declaration
    private javax.swing.JButton btnCekPaketDiGudang;
    private javax.swing.JButton btnCamera;
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JComboBox<String> comboStatus;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel labelUsername;
    private javax.swing.JLabel labelLokasi;
    private javax.swing.JPanel panelOperasi;
    private javax.swing.JTextArea txtConsole;
    private javax.swing.JTextField txtResi;
    // End of variables declaration
}