@startuml

|Pelanggan|
start
:Menyerahkan Barang;

|Petugas Loket|
:Menerima & Menimbang Barang;
:Input Data (Tujuan, Penerima, Berat);
:Sistem Generate Resi (Kapsul DTO);
:Status Paket: **"Diterima Di Loket"**;

|Kurir (Penjemput)|
if (Loket Satu Atap dengan Gudang?) then (Tidak / Soliter)
  :Scan Barcode Resi;
  note right: **Whitelist Validasi:**\nHarus "Diterima Di Loket"
  :Status Paket: **"Dibawa Kurir"**;
  :Serah Terima ke Gudang;
else (Ya)
endif

|Staf Gudang|
:Scan Barcode Kedatangan;
:Status Paket: **"Tiba di Fasilitas Sortir"**;
:Melakukan Proses Sortir (Routing);
:Status Paket: **"Sedang Disortir"**;
:Menyiapkan Kantong/Keranjang Pengiriman;
:Status Paket: **"Transit Gudang"**;

|Kurir (Long Distance)|
:Scan Barcode Ambil Muatan;
note right: **Whitelist Validasi:**\nHarus "Transit Gudang"
:Status Paket: **"Dibawa Kurir"**;
:Perjalanan Distribusi Lintas Fasilitas;

if (Kendala Lapangan / Gagal Kirim?) then (Ya)
  :Tekan Tombol Retur Gudang;
  |Staf Gudang|
  :Menerima Kembali Muatan;
  :Status Paket: **"Transit Gudang"**;
  detach
else (Tidak)
  |Kurir (Long Distance)|
  :Serah Terima di Fasilitas Tujuan Akhir;
  :Tekan Tombol Selesai;
  note right: **State Machine Validasi:**\nHarus berstatus "Dibawa Kurir"
  :Status Paket: **"Paket Telah Diterima"**;
  stop
endif

@enduml