@startuml
package "ekspedisi.model" <<Folder>> {

    class DatabaseConfig <<Singleton>> {
        - static conn : Connection
        + static getConnection() : Connection
        + static isConnected() : boolean
        + static forceCloseConn() : void
    }

    package "entity" <<Folder>> {
        class User {
            - id : String
            - username : String
            - passwordHash : String
            - role : String
            - location : String
        }

        class Paket {
            - resiId : String
            - senderName : String
            - originCity : String
            - receiverName : String
            - destinationCity : String
            - destinationAddress : String
            - weight : double
            - volume : double
            - typePaket : String
            - createdAt : LocalDateTime
            + calculateVolumetricWeight() : double
            + getChargeableWeight() : double
        }

        class ShipmentLog {
            - logId : int
            - resiId : String
            - location : String
            - status : String
            - timestamp : LocalDateTime
            - userId : String
        }

        class PaketDTO <<record>> {
            + resi : String
            + status : String
            + senderName : String
            + destinationCity : String
        }
    }

    package "dao" <<Folder>> {
        interface UserDAO <<Interface>> {
            + authenticate(username: String, pass: String): User
            + getUserById(id: String): User
            + insertUser(user: User): boolean
            + updateUser(user: User): boolean
            + deleteUser(userId: String): boolean
        }

        interface PaketDAO <<Interface>> {
            + insertPaket(paket: Paket): boolean
            + getPaketByResi(resiId: String): Paket
        }

        interface TrackingDAO <<Interface>> {
            + insertLog(log: ShipmentLog): boolean
            + getShipmentLogByResi(resiId: String): List<ShipmentLog>
            + getResiByMultipleLatestStatuses(targets: List<String>, userId: String): List<PaketDTO>
            + getAllPaketByStatus(target: String, userId: String): List<PaketDTO>
            + getLatestPaketStatusByResi(resiId: String): String
        }

        class UserDAOMariaDb
        class PaketDAOMariaDb
        class TrackingDAOMariaDb
    }
}

UserDAO <|.. UserDAOMariaDb
PaketDAO <|.. PaketDAOMariaDb
TrackingDAO <|.. TrackingDAOMariaDb

DatabaseConfig <.. UserDAOMariaDb : <<uses>>
DatabaseConfig <.. PaketDAOMariaDb : <<uses>>
DatabaseConfig <.. TrackingDAOMariaDb : <<uses>>

PaketDAO ..> Paket : <<manage>>
TrackingDAO ..> ShipmentLog : <<manage>>
TrackingDAO ..> PaketDTO : <<returns>>
UserDAO ..> User : <<manage>>

'Legenda
legend bottom center
      <b>Legend Visibilitas:</b>
      <color:red>🟥</color>  <b> - </b>  Private
      <color:blue>🔷</color>  <b> ~ </b>  Package Private
      <color:orange>🔶</color>  <b> # </b>  Protected
      <color:green>🟢</color>  <b> + </b>  Public
endlegend
@enduml